{{- $fullname := include "app.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ $fullname }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app: {{ $fullname }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
